### ISSUE TITLE
setState() on a State object for a widget that no longer appears in the widget tree

### ISSUE THREAD

**Issue by Appiq-Solutions** [sil-main-coo/overflow_text_animated#1]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _OverflowTextAnimatedState#9c500(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
#2      _OverflowTextAnimatedState._autoScroll (package:overflow_text_animated/overflow_text_animated.dart:132:5)
#3      _OverflowTextAnimatedState._handlerInfiniteLoop.<anonymous closure> (package:overflow_text_animated/overflow_text_animated.dart:126:7)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose(): _OverflowTextAnimatedState#36315(lifecycle state: defunct, not mounted)

**Comment by sil-main-coo** [comment]
Thanks for report. I will check it

**Comment by ShoaibIrfan** [comment]
> Thanks for report. I will check it

I am also facing the same exception. Is there any solution?
